/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_usuarios_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_usuarios_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_usuarios_me_patch"];
        trace?: never;
    };
    "/admin/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Usuarios */
        get: operations["listar_usuarios_admin_usuarios_get"];
        put?: never;
        /** Criar Staff */
        post: operations["criar_staff_admin_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usuarios/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Usuario */
        get: operations["obter_usuario_admin_usuarios__user_id__get"];
        put?: never;
        post?: never;
        /** Deletar Usuario */
        delete: operations["deletar_usuario_admin_usuarios__user_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Staff */
        patch: operations["atualizar_staff_admin_usuarios__user_id__patch"];
        trace?: never;
    };
    "/trilhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trilha Read Multi
         * @description Read multiple Trilha rows from the database.
         *
         *     **Pagination Options:**
         *     - Use `page` & `itemsPerPage` for paginated results
         *     - Use `offset` & `limit` for specific ranges
         *
         *     **Sorting:**
         *     - Use `sort` parameter to sort results by one or more fields
         *     - Format: `field1,-field2` (comma-separated, `-` prefix for descending)
         *     - Examples: `name` (ascending), `-age` (descending), `name,-age` (mixed)
         *
         *     **Response Format:**
         *     - Returns paginated response when using page/itemsPerPage
         *     - Returns simple list response when using offset/limit
         */
        get: operations["trilha_read_multi_trilhas_get"];
        put?: never;
        /**
         * Trilha Create
         * @description Create a new Trilha row in the database.
         */
        post: operations["trilha_create_trilhas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trilhas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trilha Read
         * @description Read a single Trilha row from the database by its primary keys: ['id'].
         */
        get: operations["trilha_read_trilhas__id__get"];
        put?: never;
        post?: never;
        /**
         * Trilha Delete
         * @description Delete a Trilha row from the database by its primary keys: ['id'].
         */
        delete: operations["trilha_delete_trilhas__id__delete"];
        options?: never;
        head?: never;
        /**
         * Trilha Update
         * @description Update an existing Trilha row in the database by its primary keys: ['id'].
         */
        patch: operations["trilha_update_trilhas__id__patch"];
        trace?: never;
    };
    "/modulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modulo Read Multi
         * @description Read multiple Modulo rows from the database.
         *
         *     **Pagination Options:**
         *     - Use `page` & `itemsPerPage` for paginated results
         *     - Use `offset` & `limit` for specific ranges
         *
         *     **Sorting:**
         *     - Use `sort` parameter to sort results by one or more fields
         *     - Format: `field1,-field2` (comma-separated, `-` prefix for descending)
         *     - Examples: `name` (ascending), `-age` (descending), `name,-age` (mixed)
         *
         *     **Response Format:**
         *     - Returns paginated response when using page/itemsPerPage
         *     - Returns simple list response when using offset/limit
         */
        get: operations["modulo_read_multi_modulos_get"];
        put?: never;
        /**
         * Modulo Create
         * @description Create a new Modulo row in the database.
         */
        post: operations["modulo_create_modulos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modulos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modulo Read
         * @description Read a single Modulo row from the database by its primary keys: ['id'].
         */
        get: operations["modulo_read_modulos__id__get"];
        put?: never;
        post?: never;
        /**
         * Modulo Delete
         * @description Delete a Modulo row from the database by its primary keys: ['id'].
         */
        delete: operations["modulo_delete_modulos__id__delete"];
        options?: never;
        head?: never;
        /**
         * Modulo Update
         * @description Update an existing Modulo row in the database by its primary keys: ['id'].
         */
        patch: operations["modulo_update_modulos__id__patch"];
        trace?: never;
    };
    "/conteudos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conteudo Read Multi
         * @description Read multiple Conteudo rows from the database.
         *
         *     **Pagination Options:**
         *     - Use `page` & `itemsPerPage` for paginated results
         *     - Use `offset` & `limit` for specific ranges
         *
         *     **Sorting:**
         *     - Use `sort` parameter to sort results by one or more fields
         *     - Format: `field1,-field2` (comma-separated, `-` prefix for descending)
         *     - Examples: `name` (ascending), `-age` (descending), `name,-age` (mixed)
         *
         *     **Response Format:**
         *     - Returns paginated response when using page/itemsPerPage
         *     - Returns simple list response when using offset/limit
         */
        get: operations["conteudo_read_multi_conteudos_get"];
        put?: never;
        /**
         * Conteudo Create
         * @description Create a new Conteudo row in the database.
         */
        post: operations["conteudo_create_conteudos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conteudos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conteudo Read
         * @description Read a single Conteudo row from the database by its primary keys: ['id'].
         */
        get: operations["conteudo_read_conteudos__id__get"];
        put?: never;
        post?: never;
        /**
         * Conteudo Delete
         * @description Delete a Conteudo row from the database by its primary keys: ['id'].
         */
        delete: operations["conteudo_delete_conteudos__id__delete"];
        options?: never;
        head?: never;
        /**
         * Conteudo Update
         * @description Update an existing Conteudo row in the database by its primary keys: ['id'].
         */
        patch: operations["conteudo_update_conteudos__id__patch"];
        trace?: never;
    };
    "/questoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Questao Read Multi
         * @description Read multiple Questao rows from the database.
         *
         *     **Pagination Options:**
         *     - Use `page` & `itemsPerPage` for paginated results
         *     - Use `offset` & `limit` for specific ranges
         *
         *     **Sorting:**
         *     - Use `sort` parameter to sort results by one or more fields
         *     - Format: `field1,-field2` (comma-separated, `-` prefix for descending)
         *     - Examples: `name` (ascending), `-age` (descending), `name,-age` (mixed)
         *
         *     **Response Format:**
         *     - Returns paginated response when using page/itemsPerPage
         *     - Returns simple list response when using offset/limit
         */
        get: operations["questao_read_multi_questoes_get"];
        put?: never;
        /**
         * Questao Create
         * @description Create a new Questao row in the database.
         */
        post: operations["questao_create_questoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Questao Read
         * @description Read a single Questao row from the database by its primary keys: ['id'].
         */
        get: operations["questao_read_questoes__id__get"];
        put?: never;
        post?: never;
        /**
         * Questao Delete
         * @description Delete a Questao row from the database by its primary keys: ['id'].
         */
        delete: operations["questao_delete_questoes__id__delete"];
        options?: never;
        head?: never;
        /**
         * Questao Update
         * @description Update an existing Questao row in the database by its primary keys: ['id'].
         */
        patch: operations["questao_update_questoes__id__patch"];
        trace?: never;
    };
    "/alternativas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alternativa Read Multi
         * @description Read multiple Alternativa rows from the database.
         *
         *     **Pagination Options:**
         *     - Use `page` & `itemsPerPage` for paginated results
         *     - Use `offset` & `limit` for specific ranges
         *
         *     **Sorting:**
         *     - Use `sort` parameter to sort results by one or more fields
         *     - Format: `field1,-field2` (comma-separated, `-` prefix for descending)
         *     - Examples: `name` (ascending), `-age` (descending), `name,-age` (mixed)
         *
         *     **Response Format:**
         *     - Returns paginated response when using page/itemsPerPage
         *     - Returns simple list response when using offset/limit
         */
        get: operations["alternativa_read_multi_alternativas_get"];
        put?: never;
        /**
         * Alternativa Create
         * @description Create a new Alternativa row in the database.
         */
        post: operations["alternativa_create_alternativas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alternativas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alternativa Read
         * @description Read a single Alternativa row from the database by its primary keys: ['id'].
         */
        get: operations["alternativa_read_alternativas__id__get"];
        put?: never;
        post?: never;
        /**
         * Alternativa Delete
         * @description Delete a Alternativa row from the database by its primary keys: ['id'].
         */
        delete: operations["alternativa_delete_alternativas__id__delete"];
        options?: never;
        head?: never;
        /**
         * Alternativa Update
         * @description Update an existing Alternativa row in the database by its primary keys: ['id'].
         */
        patch: operations["alternativa_update_alternativas__id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlternativaCreate */
        AlternativaCreate: {
            /** Questao Id */
            questao_id: number;
            /** Texto */
            texto: string;
            /**
             * Correta
             * @default false
             */
            correta: boolean;
        };
        /** AlternativaRead */
        AlternativaRead: {
            /** Id */
            id: number;
            /** Questao Id */
            questao_id: number;
            /** Texto */
            texto: string;
            /** Correta */
            correta: boolean;
        };
        /** AlternativaUpdate */
        AlternativaUpdate: {
            /** Texto */
            texto?: string | null;
            /** Correta */
            correta?: boolean | null;
        };
        /** ConteudoCreate */
        ConteudoCreate: {
            /** Modulo Id */
            modulo_id: number;
            /** Titulo */
            titulo: string;
            tipo: components["schemas"]["ConteudoTipo"];
            /** Ordem */
            ordem: number;
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /** ConteudoRead */
        ConteudoRead: {
            /** Id */
            id: number;
            /** Modulo Id */
            modulo_id: number;
            /** Titulo */
            titulo: string;
            tipo: components["schemas"]["ConteudoTipo"];
            /** Ordem */
            ordem: number;
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /**
         * ConteudoTipo
         * @enum {string}
         */
        ConteudoTipo: "video" | "artigo" | "quiz";
        /** ConteudoUpdate */
        ConteudoUpdate: {
            /** Titulo */
            titulo?: string | null;
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModuloCreate */
        ModuloCreate: {
            /** Trilha Id */
            trilha_id: number;
            /** Titulo */
            titulo: string;
            /** Ordem */
            ordem: number;
        };
        /** ModuloRead */
        ModuloRead: {
            /** Id */
            id: number;
            /** Trilha Id */
            trilha_id: number;
            /** Titulo */
            titulo: string;
            /** Ordem */
            ordem: number;
        };
        /** ModuloUpdate */
        ModuloUpdate: {
            /** Titulo */
            titulo?: string | null;
        };
        /** QuestaoCreate */
        QuestaoCreate: {
            /** Conteudo Id */
            conteudo_id: number;
            /** Ordem */
            ordem: number;
            /** Enunciado */
            enunciado: string;
        };
        /** QuestaoRead */
        QuestaoRead: {
            /** Id */
            id: number;
            /** Conteudo Id */
            conteudo_id: number;
            /** Ordem */
            ordem: number;
            /** Enunciado */
            enunciado: string;
        };
        /** QuestaoUpdate */
        QuestaoUpdate: {
            /** Enunciado */
            enunciado?: string | null;
        };
        /** RefreshInput */
        RefreshInput: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RoleUsuario
         * @enum {string}
         */
        RoleUsuario: "aluno" | "author" | "admin";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TrilhaCreate */
        TrilhaCreate: {
            /** Titulo */
            titulo: string;
            /** Descricao */
            descricao?: string | null;
            /** Foto */
            foto?: string | null;
        };
        /** TrilhaRead */
        TrilhaRead: {
            /** Id */
            id: number;
            /** Titulo */
            titulo: string;
            /** Descricao */
            descricao?: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** TrilhaUpdate */
        TrilhaUpdate: {
            /** Titulo */
            titulo?: string | null;
            /** Descricao */
            descricao?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UsuarioAdminUpdate */
        UsuarioAdminUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            role?: components["schemas"]["RoleUsuario"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UsuarioCreate */
        UsuarioCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsuarioLogin */
        UsuarioLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsuarioRead */
        UsuarioRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["RoleUsuario"];
        };
        /** UsuarioStaffCreate */
        UsuarioStaffCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["RoleUsuario"];
        };
        /** UsuarioUpdate */
        UsuarioUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** DynamicListResponse */
        fastcrud__core__pagination__DynamicListResponse__1: {
            /** Data */
            data: components["schemas"]["TrilhaRead"][];
        };
        /** DynamicListResponse */
        fastcrud__core__pagination__DynamicListResponse__2: {
            /** Data */
            data: components["schemas"]["ModuloRead"][];
        };
        /** DynamicListResponse */
        fastcrud__core__pagination__DynamicListResponse__3: {
            /** Data */
            data: components["schemas"]["ConteudoRead"][];
        };
        /** DynamicListResponse */
        fastcrud__core__pagination__DynamicListResponse__4: {
            /** Data */
            data: components["schemas"]["QuestaoRead"][];
        };
        /** DynamicListResponse */
        fastcrud__core__pagination__DynamicListResponse__5: {
            /** Data */
            data: components["schemas"]["AlternativaRead"][];
        };
        /** DynamicPaginatedResponse */
        fastcrud__core__pagination__DynamicPaginatedResponse__1: {
            /** Data */
            data: components["schemas"]["TrilhaRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** DynamicPaginatedResponse */
        fastcrud__core__pagination__DynamicPaginatedResponse__2: {
            /** Data */
            data: components["schemas"]["ModuloRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** DynamicPaginatedResponse */
        fastcrud__core__pagination__DynamicPaginatedResponse__3: {
            /** Data */
            data: components["schemas"]["ConteudoRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** DynamicPaginatedResponse */
        fastcrud__core__pagination__DynamicPaginatedResponse__4: {
            /** Data */
            data: components["schemas"]["QuestaoRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** DynamicPaginatedResponse */
        fastcrud__core__pagination__DynamicPaginatedResponse__5: {
            /** Data */
            data: components["schemas"]["AlternativaRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_usuarios_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
        };
    };
    delete_me_usuarios_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_usuarios_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_admin_usuarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"][];
                };
            };
        };
    };
    criar_staff_admin_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioStaffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_usuario_admin_usuarios__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_usuario_admin_usuarios__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_staff_admin_usuarios__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trilha_read_multi_trilhas_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number | null;
                page?: number | null;
                itemsPerPage?: number | null;
                sort?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["fastcrud__core__pagination__DynamicPaginatedResponse__1"] | components["schemas"]["fastcrud__core__pagination__DynamicListResponse__1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trilha_create_trilhas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrilhaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trilha_read_trilhas__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrilhaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trilha_delete_trilhas__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trilha_update_trilhas__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrilhaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modulo_read_multi_modulos_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number | null;
                page?: number | null;
                itemsPerPage?: number | null;
                sort?: string | null;
                trilha_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["fastcrud__core__pagination__DynamicPaginatedResponse__2"] | components["schemas"]["fastcrud__core__pagination__DynamicListResponse__2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modulo_create_modulos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuloCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modulo_read_modulos__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modulo_delete_modulos__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modulo_update_modulos__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuloUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conteudo_read_multi_conteudos_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number | null;
                page?: number | null;
                itemsPerPage?: number | null;
                sort?: string | null;
                modulo_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["fastcrud__core__pagination__DynamicPaginatedResponse__3"] | components["schemas"]["fastcrud__core__pagination__DynamicListResponse__3"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conteudo_create_conteudos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConteudoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conteudo_read_conteudos__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteudoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conteudo_delete_conteudos__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conteudo_update_conteudos__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConteudoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questao_read_multi_questoes_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number | null;
                page?: number | null;
                itemsPerPage?: number | null;
                sort?: string | null;
                conteudo_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["fastcrud__core__pagination__DynamicPaginatedResponse__4"] | components["schemas"]["fastcrud__core__pagination__DynamicListResponse__4"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questao_create_questoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestaoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questao_read_questoes__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestaoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questao_delete_questoes__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questao_update_questoes__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestaoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternativa_read_multi_alternativas_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number | null;
                page?: number | null;
                itemsPerPage?: number | null;
                sort?: string | null;
                questao_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["fastcrud__core__pagination__DynamicPaginatedResponse__5"] | components["schemas"]["fastcrud__core__pagination__DynamicListResponse__5"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternativa_create_alternativas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlternativaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternativa_read_alternativas__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternativa_delete_alternativas__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternativa_update_alternativas__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlternativaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
