/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_usuarios_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_usuarios_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_usuarios_me_patch"];
        trace?: never;
    };
    "/trilhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Trilhas */
        get: operations["listar_trilhas_trilhas_get"];
        put?: never;
        /** Criar Trilha */
        post: operations["criar_trilha_trilhas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trilhas/{trilha_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Trilha */
        get: operations["obter_trilha_trilhas__trilha_id__get"];
        put?: never;
        post?: never;
        /** Deletar Trilha */
        delete: operations["deletar_trilha_trilhas__trilha_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Trilha */
        patch: operations["atualizar_trilha_trilhas__trilha_id__patch"];
        trace?: never;
    };
    "/trilhas/{trilha_id}/modulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Modulos */
        get: operations["listar_modulos_trilhas__trilha_id__modulos_get"];
        put?: never;
        /** Criar Modulo */
        post: operations["criar_modulo_trilhas__trilha_id__modulos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modulos/{modulo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Modulo */
        get: operations["obter_modulo_modulos__modulo_id__get"];
        put?: never;
        post?: never;
        /** Deletar Modulo */
        delete: operations["deletar_modulo_modulos__modulo_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Modulo */
        patch: operations["atualizar_modulo_modulos__modulo_id__patch"];
        trace?: never;
    };
    "/modulos/{modulo_id}/conteudos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Conteudos */
        get: operations["listar_conteudos_modulos__modulo_id__conteudos_get"];
        put?: never;
        /** Criar Conteudo */
        post: operations["criar_conteudo_modulos__modulo_id__conteudos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conteudos/{conteudo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Conteudo */
        get: operations["obter_conteudo_conteudos__conteudo_id__get"];
        put?: never;
        post?: never;
        /** Deletar Conteudo */
        delete: operations["deletar_conteudo_conteudos__conteudo_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Conteudo */
        patch: operations["atualizar_conteudo_conteudos__conteudo_id__patch"];
        trace?: never;
    };
    "/conteudos/{conteudo_id}/questoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Questoes */
        get: operations["listar_questoes_conteudos__conteudo_id__questoes_get"];
        put?: never;
        /** Criar Questao */
        post: operations["criar_questao_conteudos__conteudo_id__questoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questoes/{questao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Questao */
        get: operations["obter_questao_questoes__questao_id__get"];
        put?: never;
        post?: never;
        /** Deletar Questao */
        delete: operations["deletar_questao_questoes__questao_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Questao */
        patch: operations["atualizar_questao_questoes__questao_id__patch"];
        trace?: never;
    };
    "/questoes/{questao_id}/alternativas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Alternativas */
        get: operations["listar_alternativas_questoes__questao_id__alternativas_get"];
        put?: never;
        /** Criar Alternativa */
        post: operations["criar_alternativa_questoes__questao_id__alternativas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alternativas/{alternativa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Alternativa */
        get: operations["obter_alternativa_alternativas__alternativa_id__get"];
        put?: never;
        post?: never;
        /** Deletar Alternativa */
        delete: operations["deletar_alternativa_alternativas__alternativa_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Alternativa */
        patch: operations["atualizar_alternativa_alternativas__alternativa_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlternativaCreate */
        AlternativaCreate: {
            /** Texto */
            texto: string;
            /**
             * Correta
             * @default false
             */
            correta: boolean;
        };
        /** AlternativaRead */
        AlternativaRead: {
            /** Id */
            id: number;
            /** Questao Id */
            questao_id: number;
            /** Texto */
            texto: string;
            /** Correta */
            correta: boolean;
        };
        /** AlternativaUpdate */
        AlternativaUpdate: {
            /** Texto */
            texto?: string | null;
            /** Correta */
            correta?: boolean | null;
        };
        /** ConteudoCreate */
        ConteudoCreate: {
            /** Titulo */
            titulo: string;
            tipo: components["schemas"]["ConteudoTipo"];
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /** ConteudoRead */
        ConteudoRead: {
            /** Id */
            id: number;
            /** Modulo Id */
            modulo_id: number;
            /** Titulo */
            titulo: string;
            tipo: components["schemas"]["ConteudoTipo"];
            /** Ordem */
            ordem: number;
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /**
         * ConteudoTipo
         * @enum {string}
         */
        ConteudoTipo: "video" | "artigo" | "quiz";
        /** ConteudoUpdate */
        ConteudoUpdate: {
            /** Titulo */
            titulo?: string | null;
            /** Video Url */
            video_url?: string | null;
            /** Artigo Texto */
            artigo_texto?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModuloCreate */
        ModuloCreate: {
            /** Titulo */
            titulo: string;
        };
        /** ModuloRead */
        ModuloRead: {
            /** Id */
            id: number;
            /** Trilha Id */
            trilha_id: number;
            /** Titulo */
            titulo: string;
            /** Ordem */
            ordem: number;
        };
        /** ModuloUpdate */
        ModuloUpdate: {
            /** Titulo */
            titulo?: string | null;
        };
        /** Page[TrilhaRead] */
        Page_TrilhaRead_: {
            /** Items */
            items: components["schemas"]["TrilhaRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** QuestaoCreate */
        QuestaoCreate: {
            /** Enunciado */
            enunciado: string;
        };
        /** QuestaoRead */
        QuestaoRead: {
            /** Id */
            id: number;
            /** Conteudo Id */
            conteudo_id: number;
            /** Ordem */
            ordem: number;
            /** Enunciado */
            enunciado: string;
        };
        /** QuestaoUpdate */
        QuestaoUpdate: {
            /** Enunciado */
            enunciado?: string | null;
        };
        /** TrilhaCreate */
        TrilhaCreate: {
            /** Titulo */
            titulo: string;
            /** Descricao */
            descricao?: string | null;
        };
        /** TrilhaRead */
        TrilhaRead: {
            /** Id */
            id: number;
            /** Titulo */
            titulo: string;
            /** Descricao */
            descricao?: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** TrilhaUpdate */
        TrilhaUpdate: {
            /** Titulo */
            titulo?: string | null;
            /** Descricao */
            descricao?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UsuarioCreate */
        UsuarioCreate: {
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
        };
        /** UsuarioLogin */
        UsuarioLogin: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** UsuarioRead */
        UsuarioRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** UsuarioUpdate */
        UsuarioUpdate: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_usuarios_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
        };
    };
    delete_me_usuarios_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_usuarios_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_trilhas_trilhas_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TrilhaRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_trilha_trilhas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrilhaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrilhaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_trilha_trilhas__trilha_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trilha_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrilhaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_trilha_trilhas__trilha_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trilha_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_trilha_trilhas__trilha_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trilha_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrilhaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrilhaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_modulos_trilhas__trilha_id__modulos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trilha_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_modulo_trilhas__trilha_id__modulos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trilha_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuloCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_modulo_modulos__modulo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modulo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_modulo_modulos__modulo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modulo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_modulo_modulos__modulo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modulo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuloUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuloRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_conteudos_modulos__modulo_id__conteudos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modulo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteudoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_conteudo_modulos__modulo_id__conteudos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modulo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConteudoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteudoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_conteudo_conteudos__conteudo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conteudo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteudoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_conteudo_conteudos__conteudo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conteudo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_conteudo_conteudos__conteudo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conteudo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConteudoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConteudoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_questoes_conteudos__conteudo_id__questoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conteudo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestaoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_questao_conteudos__conteudo_id__questoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conteudo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestaoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestaoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_questao_questoes__questao_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questao_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestaoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_questao_questoes__questao_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questao_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_questao_questoes__questao_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questao_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestaoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestaoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_alternativas_questoes__questao_id__alternativas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questao_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativaRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_alternativa_questoes__questao_id__alternativas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questao_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlternativaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_alternativa_alternativas__alternativa_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alternativa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletar_alternativa_alternativas__alternativa_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alternativa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_alternativa_alternativas__alternativa_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alternativa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlternativaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlternativaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
