"""conquista_atualizado

Revision ID: 239539aee576
Revises: 4c7f945b2d7f
Create Date: 2026-09-12 04:30:08.643255

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239539aee576'
down_revision: Union[str, Sequence[str], None] = '4c7f945b2d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associacao_conquista_usuario',
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquistas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('conquista_id', 'usuario_id')
    )
    op.drop_table('conquista_adquirida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conquista_adquirida',
    sa.Column('conquista_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquistas.id'], name=op.f('conquista_adquirida_conquista_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('conquista_adquirida_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('conquista_id', 'usuario_id', name=op.f('conquista_adquirida_pkey'))
    )
    op.drop_table('associacao_conquista_usuario')
    # ### end Alembic commands ###
