"""trilha com foto

Revision ID: 4c7f945b2d7f
Revises: e023ca74d8af
Create Date: 2026-09-10 11:43:25.233492

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7f945b2d7f'
down_revision: Union[str, Sequence[str], None] = 'e023ca74d8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trilhas', sa.Column('foto', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trilhas', 'foto')
    # ### end Alembic commands ###
