"""role no usuario

Revision ID: 55fde3692917
Revises: ea9a8d412372
Create Date: 2026-09-10 03:20:57.479026

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55fde3692917'
down_revision: Union[str, Sequence[str], None] = 'ea9a8d412372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('aluno', 'author', 'admin', name='roleusuario').create(op.get_bind())
    op.add_column('usuarios', sa.Column('role', postgresql.ENUM('aluno', 'author', 'admin', name='roleusuario', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    sa.Enum('aluno', 'author', 'admin', name='roleusuario').drop(op.get_bind())
    # ### end Alembic commands ###
