"""add tag to trilha

Revision ID: a6d2fd16b5c2
Revises: e24fd625cde6
Create Date: 2026-09-12 23:15:58.138013

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d2fd16b5c2'
down_revision: Union[str, Sequence[str], None] = 'e24fd625cde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trilhas', sa.Column('tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trilhas', 'tag')
    # ### end Alembic commands ###
