"""teste reset migrations

Revision ID: be81cd67342b
Revises: 
Create Date: 2026-09-14 12:19:29.824065

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be81cd67342b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('litros', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conquistas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_dir', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', postgresql.ENUM('aluno', 'author', 'admin', name='roleusuario', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('associacao_conquista_usuario',
    sa.Column('conquista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conquista_id'], ['conquistas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('conquista_id', 'usuario_id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('tipo', postgresql.ENUM('video', 'artigo', 'quiz', name='conteudotipo', create_type=False), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('artigo_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativas')
    op.drop_table('questoes')
    op.drop_table('conteudos')
    op.drop_table('modulos')
    op.drop_table('associacao_conquista_usuario')
    op.drop_table('usuarios')
    op.drop_table('trilhas')
    op.drop_table('conquistas')
    op.drop_table('aquarios')
    # ### end Alembic commands ###
