"""cria tabela de aceite de termos

Revision ID: e1930ec7d5c6
Revises: 4500174e6b0c
Create Date: 2026-09-25 05:35:01.365349

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1930ec7d5c6'
down_revision: Union[str, Sequence[str], None] = 'be81cd67342b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aceites_termos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('termos_versao', sa.String(length=20), nullable=False),
    sa.Column('privacidade_versao', sa.String(length=20), nullable=False),
    sa.Column('aceito_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aceites_termos')
    # ### end Alembic commands ###
