"""add pontos to conteudo

Revision ID: e24fd625cde6
Revises: 4c7f945b2d7f
Create Date: 2026-09-12 04:48:05.619052

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24fd625cde6'
down_revision: Union[str, Sequence[str], None] = '4c7f945b2d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conteudos', sa.Column('pontos', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conteudos', 'pontos')
    # ### end Alembic commands ###
