"""create logs

Revision ID: e38ff668d53d
Revises: be81cd67342b
Create Date: 2026-09-25 01:05:50.890826

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38ff668d53d'
down_revision: Union[str, Sequence[str], None] = 'be81cd67342b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('create', 'update', 'delete', name='acaoauditoria').create(op.get_bind())
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', postgresql.ENUM('create', 'update', 'delete', name='acaoauditoria', create_type=False), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('alteracoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_auditoria')
    sa.Enum('create', 'update', 'delete', name='acaoauditoria').drop(op.get_bind())
    # ### end Alembic commands ###
