"""trilhas com modulos e conteudos

Revision ID: ea9a8d412372
Revises: f2b8e285a0a3
Create Date: 2026-09-09 04:50:23.141645

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9a8d412372'
down_revision: Union[str, Sequence[str], None] = 'f2b8e285a0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('video', 'artigo', 'quiz', name='conteudotipo'), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('artigo_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternativas')
    op.drop_table('questoes')
    op.drop_table('conteudos')
    op.drop_table('modulos')
    op.drop_table('trilhas')
    # ### end Alembic commands ###
